name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run lint

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm test

  deployment:
    name: 'Deployment'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test]

    if: github.ref == 'refs/heads/main'

    environment:
      name: production
      url: https://autoskolaberan.cz

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run deploy
